[package]
name = "program-interfaces"
version = "0.1.0"
edition.workspace = true

[features]
default = ["no-entrypoint"]
no-entrypoint = []

[dependencies]
anchor-lang = { workspace = true }
bytemuck = { workspace = true }