name: Publish to crates.io

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish_audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        run: |-
          cargo release \
            publish \
            --all-features \
            --allow-branch main \
            --no-confirm \
            --execute
